warehouseDRF/ACCOUNTING/ACCOUNTING/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from shop.views import *
from regusers.views import *
from shop.views_goods_api import *
from rest_framework import routers
from django.conf.urls.static import static
from django.conf import settings
#для jwt
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from rest_framework.routers import DefaultRouter




# router = routers.SimpleRouter()
# router.register(r'goods', GoodsViewSet)
# router = DefaultRouter()
# router.register(r'api/app_goods', ProductViewSet)




urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('shop.urls')),#тут указали стартовую страницу от которой будут идти все другие ссылки приложения
    path('', include('regusers.urls')),
    # path('api/v1/', include(router.urls)),
    # path('', include(router.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

warehouseDRF/ACCOUNTING/regusers/urls.py
from django.urls import path, re_path
from regusers.views import *

app_name = 'regusers'


urlpatterns = [
	# path('login/', LoginUser.as_view(), name='log_in'),
	# path('register/', RegisterUser.as_view(), name='register'),
	
	#урл регистрации с подтвержлением почты
	path('login/', login_user, name='login'),
    path('register/', register_user, name='register'),
    # path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', activate, name='activate'),

    path('logout/', logout_user, name='logout'),
    

	path('confirm_email/', confirm_email, name='confirm_email'),
	path('activate_user/<uidb64>/<token>/', activate_user, name='activate_user'),#тут должна быть функция, а не класс. Тут формируется урл с параметрами, мы их в шаблоне пишем при указании самой урл и потом далее параметры просто через пробел. Первый параметр <uidb64> (он кодируется через функцию кодировщик из джанго), второй параметр <token> (генерируется генератором токена из джанго). 
	
	path('invalid_verify/', invalid_verify, name='invalid_verify'),

	path('forgot_password/', forgot_password, name='forgot_password'),

	path('go_to_restore_password/', go_to_restore_password, name='go_to_restore_password'),

	path('restore_password_url/<uidb64>/<token>/', restore_password_url, name='restore_password_url'),
	path('restore_password_form/', restore_password_form, name='restore_password_form'),

]

warehouseDRF/ACCOUNTING/shop/urls.py
from django.urls import path, re_path
from shop.views import *
from shop.views_receipt import *
from shop.views_expense import *
from shop.views_inventory import *


from shop.views_order_api import *
from shop.views_goods_api import *
from shop.views_receipt_api import *
from shop.views_expense_api import *
from shop.views_inventory_api import *
from shop.views_report_api import *

# app_name = 'showcase' #если прописать название приложения, то в шаблонах придется его везде дописать через двоеточие для каждоый ссылки функции. Возможно это будет понятнее если в проекте много приложений.

urlpatterns = [

    path('', Home.as_view(), name='start'),
    #заказы
    path('synchronization_order/', synchronization, name='synchronization'),
    path('order_list/', Order_list.as_view(), name='order_list'),
    path('order_list/completed/', order_completed, name='order_completed'),
    path('order_list/not_completed/', order_not_completed, name='order_not_completed'),

    path('order_list/open/<int:order_number>/', order_list_open, name='order_list_open'),
    path('order_list/open/activate/<int:order_activate>/', order_list_activate, name='order_list_activate'),
    path('order_list/open/deactivate/<int:order_deactivate>/', order_list_deactivate, name='order_list_deactivate'),
    #товары
    path('good_list/', Goods_list.as_view(), name='goods_list'),
    path('good_list/group_show/<slug:group_slug>/', group_show, name='group_show'),
    path('good_list/add/', Goods_add.as_view(), name='goods_add'),
    path('good_list/add_group/', Group_add.as_view(), name='group_add'),
    path('good_list/goods_modify/<int:good_id>/', goods_modify, name='goods_modify'),
    path('good_list/goods_delete/<int:good_id>/', goods_delete, name='goods_delete'),
    path('good_list/group_delete/', group_delete, name='group_delete'),
    path('good_list/select_group_to_transfer/<int:group_id>/', select_group_to_transfer, name='select_group_to_transfer'),
    
    path('good_list/load_file/', goods_load_file, name='goods_load_file'),
    path('good_list/load_file/url_from_load_template/', url_from_load_template, name='url_from_load_template'),


    #приходный документ
    path('receipt/list/view/', receipt_list, name='receipt_list'),
    path('receipt/list/view/create/', receipt_document_create, name='receipt_document_create'),
    path('receipt/list/view/delete/<int:number_delete_receipt>/', receipt_document_delete, name='receipt_document_delete'),
    path('receipt/list/view/open/<int:open_receipt>/', receipt_document_open, name='receipt_document_open'),
    path('receipt/list/view/open/add_goods/<int:number_doc>/', receipt_add_goods, name='receipt_add_goods'),
    path('receipt/list/view/open/delete_goods/<int:number_delete_good>/', receipt_delete_goods, name='receipt_delete_goods'),
    path('receipt/list/view/open/edit_goods/<int:number_edit_good>/', receipt_document_edit, name='receipt_document_edit'),
    path('receipt/list/view/open/activate/<int:receipt_activate>/', receipt_document_activate, name='receipt_document_activate'),
    path('receipt/list/view/open/deactivate/<int:receipt_deactivate>/', receipt_document_deactivate, name='receipt_document_deactivate'),
    path('receipt/list/receipt_load_file/<int:number_doc>/', receipt_load_file, name='receipt_load_file'),
    path('receipt/list/receipt_add_if_not_in_base/<int:number_good>/', receipt_add_if_not_in_base, name='receipt_add_if_not_in_base'),
    path('receipt/list/receipt_change_if_not_in_base/<int:number_good>/', receipt_change_if_not_in_base, name='receipt_change_if_not_in_base'),

    #расходный документ
    path('expense/list/view/', expense_list, name='expense_list'),
    path('expense/list/view/create/', expense_document_create, name='expense_document_create'),
    path('expense/list/view/delete/<int:number_delete_expense>/', expense_document_delete, name='expense_document_delete'),
    path('expense/list/view/open/<int:open_expense>/', expense_document_open, name='expense_document_open'),
    path('expense/list/view/open/add_goods/<int:number_doc>/', expense_add_goods, name='expense_add_goods'),
    path('expense/list/view/open/delete_goods/<int:number_delete_good>/', expense_delete_goods, name='expense_delete_goods'),
    path('expense/list/view/open/activate/<int:expense_activate>/', expense_document_activate, name='expense_document_activate'),
    path('expense/list/view/open/deactivate/<int:expense_deactivate>/', expense_document_deactivate, name='expense_document_deactivate'),
    #отчеты
    path('reports/', reports, name='reports'),
    path('reports/income_report/', income_report, name='income_report'),
    path('reports/expense_report/', expense_report, name='expense_report'),
    path('reports/sales_report/', sales_report, name='sales_report'),
    path('reports/sales_report_summary/', sales_report_summary, name='sales_report_summary'),

    #инвентаризация
    path('inventory/list/view/', inventory_list, name='inventory_list'),
    path('inventory/list/view/create/', inventory_create, name='inventory_create'),
    path('inventory/list/view/open/<int:inv_number>/', inventory_open, name='inventory_open'),
    path('inventory/list/view/delete/<int:inv_number>/', inventory_delete, name='inventory_delete'),
    path('inventory/list/view/add_group/<int:inv_number>/', inventory_add_group, name='inventory_add_group'),
    path('inventory/list/view/activate/<int:inv_number>/', inventory_activate, name='inventory_activate'),
    path('inventory/list/view/deactivate/<int:inv_number>/', inventory_deactivate, name='inventory_deactivate'),
    path('inventory/list/view/receipt_load_file/<int:inv_number>/', inventory_load_file, name='inventory_load_file'),
    # path('inventory/list/view/delete_position/<int:id_good_in_inventory>/', inventory_delete_position, name='inventory_delete_position'),
    path('inventory/list/url_from_load_template_inv/', url_from_load_template_inv, name='url_from_load_template_inv'),
    path('inventory/list/url_from_load_error_inv/', url_from_load_error_inv, name='url_from_load_error_inv'),
    path('inventory/list/url_from_load_inventory/<int:inv_number>/', inventory_print, name='inventory_print'),
    path('inventory/list/delete_position_if_not_in_base/<int:id_good>/', inventory_delete_position_if_not_in_base, name='inventory_delete_position_if_not_in_base'),
    path('inventory/list/inventory_add_if_not_in_base/<int:number_good>/', inventory_add_if_not_in_base, name='inventory_add_if_not_in_base'),
    path('inventory/list/inventory_change_if_not_in_base/<int:number_good>/', inventory_change_if_not_in_base, name='inventory_change_if_not_in_base'),
    path('inventory/list/view/update_quantity/<int:number_inv>/', inventory_update_quantity, name='inventory_update_quantity'),
    path('inventory/list/view/add_all_buffer/<int:number_inv>/', inventory_add_all_buffer, name='inventory_add_all_buffer'),

    # path('group/<slug:group_slug>/', GroupShow.as_view(), name='group'),
    # path('order/list/', Order_list_view.as_view(), name='order_list'),
    # path('order/list/<int:pk>', Order_list_view.as_view(), name='order_list_c'),
    #тут будут апишные функции
    #заказы
    path('api/get_order/', Get_order.as_view(), name='get_order'),
    path('api/get_order/<int:order_number>/', Get_order_open.as_view(), name='get_order_open'),
    path('api/get_order_completed/', Get_order_completed.as_view(), name='get_order_completed'),
    path('api/get_order_not_completed/', Get_order_not_completed.as_view(), name='get_order_not_completed'),
    path('api/order_list/open/activate/<int:order_activate>/', api_order_list_activate, name='api_order_list_activate'),
    path('api/order_list/open/deactivate/<int:order_deactivate>/', api_order_list_deactivate, name='api_order_list_deactivate'),



    #товары
    path('api/get_good/', Get_good.as_view(), name='get_good'),
    path('api/get_group/', Get_group.as_view(), name='get_group'),    
    path('api/products/search/<slug:group_slug>/', Get_good_in_group.as_view(), name='get_good_in_group'),
    path('api/add_group/', Group_add_api.as_view(), name='add_group'),    
    path('api/add_good/', Goods_add_api.as_view()),    
    path('api/add_good/load_file/', Goods_load_file_api.as_view()),    
    path('api/add_good/url_from_load_template/', url_from_load_template_api),    
    path('api/upload-images/', BulkImageUploadView.as_view(), name='bulk-image-upload'),
    path('api/clean-unused-files/', CleanUnusedFilesView.as_view(), name='clean-unused-files'),
    path('api/delete_group/', Group_delete_api.as_view(), name='delete_group'),
    path('api/select_group_to_transfer/<int:group_id>', Select_group_to_transfer_api.as_view(), name='select_group_to_transfer'),
    path('api/group_without_delete/<int:group_id>', group_without_delete, name='group_without_delete'),
    path('api/goods_modify/<int:good_id>', Goods_modify_api.as_view(), name='goods_modify'),
    path('api/load_good_to_modify/<int:good_id>', load_good_to_modify, name='load_good_to_modify'),
    path('api/goods_delete/<int:good_id>', goods_delete, name='goods_delete'),
    path('api/products/search/', ProductSearchAPIView.as_view(), name='product-search'),
    
    #приходные документы
    path('api/receipt_list_view/', Get_receipt_list.as_view(), name='receipt_list_view'),
    path('api/receipt_list_create/', Receipt_document_create_api.as_view(), name='receipt_list_create'),
    path('api/receipt_list_open/<int:number_receipt>', Receipt_document_open_api.as_view(), name='receipt_list_open'),
    path('api/receipt_number_open/<int:number_receipt>', Receipt_number_open_api.as_view(), name='receipt_number_open'),
    path('api/receipt_number_open/activate/<int:receipt_activate>/', api_receipt_list_activate, name='api_receipt_list_activate'),
    path('api/receipt_number_open/deactivate/<int:receipt_deactivate>/', api_receipt_list_deactivate, name='api_receipt_list_deactivate'),

warehouseDRF/ACCOUNTING/regusers/models.py
from django.db import models

# Create your models here.

warehouseDRF/ACCOUNTING/regusers/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth.models import User

from .models import *




class RegisterUserForm(UserCreationForm):#делаем класс для формы на базе UserCreationForm, его также нужно импортировать.
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Введите имя пользователя'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input', 'placeholder': 'Придумайте пароль'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input', 'placeholder': 'Повторите пароль'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input', 'placeholder': 'Введите вашу почту'}))



    class Meta:
        model = User#пишем модель. Ее также нужно импортировать из джанго
        fields = ('username', 'email', 'password1', 'password2')#указали поля для нашей формы.
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-input'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-input'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-input'}),
        }#виджеты для назначение классов для полей, то есть стили добавлеяем через эти классы. Имена полей можно посмотреть через панель разработчика в браузере через просмотреть код на нужном нам элементе. Там есть input поля и прописаны имена полей. Они также берутся из джанго. Также можно посмотреть и имена полей для других полей, не только username и пароли. Делаем мы так, потому что мы делаем свою форму вместо стандартной. В другом фреймворке наверно можно и свои поля для своей формы указать. Далее перейдем в файл views.py и перепишем наш класс. 
        #стили для стандартных полей почему-то не работают. Поэтому нам придется переопределить эти поля и к ним дописать также виджеты со стилями. Переопределить их нужно до класса Meta. Теперь стили будут работать. Перейдем далее в шаблон и перепишем там шаблон. Добавим еще поле email в нашу форму. Теперь можно регать новых пользователей. Выглядит совсем все стандартно.  


class LoginUserForm(AuthenticationForm):#название сами придумали, базовый класс нужно также импортировать дополинетльно. 
    #ниже мы определели поля для ввода логина и пароля и прописали к ним виджеты для стилей css. 
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Введите имя пользователя'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input', 'placeholder': 'Введите пароль'}))
# placeholder - это надпись в строке ввода
    class Meta:
        model = User#взяли пользователя из джанго. К нему можно и дополнительные поля приделать через класс модели. То есть в файле models можно прописать класс и сделать класс из джанго как родитель и дописать к нему доп поля
        fields = ('username', 'password')


class Forgot_passwordForm(PasswordResetForm):    
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input', 'placeholder': 'Введите вашу почту'}))

    class Meta:
        model = User
        fields = ('email', )




class Restore_passwordForm(SetPasswordForm):
    new_password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input', 'placeholder': 'Придумайте пароль'}))
    new_password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input', 'placeholder': 'Повторите пароль'}))

    class Meta:
        model = User
        fields = ('password1', 'password2')

    

warehouseDRF/ACCOUNTING/regusers/templates/regusers/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }}, 
Please click on the link to confirm your registration, 
http://{{ domain }}{% url 'activate' uidb64=uid token=token %} 
{% endautoescape %}

warehouseDRF/ACCOUNTING/regusers/templates/regusers/check_email.html
{% extends 'showcase/start.html' %}

{% block content %}

<br><br><br><br><br><br>

<h5>{{ t }}</h5>

<a href="{% url 'start' %}"><h5>Вернуться на главную страницу</h5></a>


{% endblock %}

warehouseDRF/ACCOUNTING/regusers/templates/regusers/forgot_password.html
{% extends 'showcase/start.html' %}

{% block content %}

<br><br><br><br><br><br>

<form action="{% url 'regusers:forgot_password' %}" method="post">
 {% csrf_token %}

<p><label class="form-label" for="{{ form.email.id_for_label }}">Почта: </label>{{ form.email }}</p>

<div class="form-error">{{ f.errors }}</div>

<button type="submit">Восстановить пароль</button>

</form>

{% endblock %}

warehouseDRF/ACCOUNTING/regusers/templates/regusers/go_to_restore_password.html
{% extends 'showcase/start.html' %}

{% block content %}

<br><br><br><br><br><br>


<h1>{{ s }}</h1>




{% endblock %}

warehouseDRF/ACCOUNTING/regusers/templates/regusers/invalid_verify.html
{% extends 'showcase/start.html' %}

{% block content %}

<br><br><br><br><br><br>

<h1>Ссылка не верна</h1>



{% endblock %}

warehouseDRF/ACCOUNTING/regusers/templates/regusers/login.html
{% extends 'showcase/start.html' %}
 
{% block content %}

<h1>{{title}}</h1>
 
<form action="{% url 'regusers:login' %}" method="post">
    {% csrf_token %}
    
<div class="form-error">{{ form.non_field_errors }}</div>
 
{% for f in form %}

<div>

<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>

</div>

<div class="form-error">{{ f.errors }}</div>
{% endfor %}


    <button type="submit">Войти</button>

    <a href="{% url 'regusers:forgot_password' %}"><h3>Забыли пароль?</h3></a>

<a href="{% url 'regusers:register' %}"><h3>Перейти на страницу регистрации</h3></a>

</form>
 
{% endblock %}

warehouseDRF/ACCOUNTING/regusers/templates/regusers/new_password.html
{% extends 'showcase/start.html' %}

{% block content %}

<br><br><br><br><br><br>

<form action="{% url 'regusers:restore_password_form' %}" method="post">
 {% csrf_token %}

 {{form.as_p}} 


<div class="form-error">{{ form.errors }}</div>

<button type="submit">Сохранить изменения</button>

</form>

{% endblock %}

warehouseDRF/ACCOUNTING/regusers/templates/regusers/register.html
{% extends 'showcase/start.html' %}
 
{% block content %}
<h1>{{title}}</h1>

<!-- атрибут action не стали прописывать, так как перенаправление будем делать на ту же самую форму в случае если пользователь введет что то не так  -->
<form action="{% url 'regusers:register' %}" method="post">
    {% csrf_token %}
    
<!-- перебираем вручную поля формы. Скорее всего берется просто привязанная форма из класса в файле views.py -->
{% for f in form %}

<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>

<div class="form-error">{{ f.errors }}</div>
{% endfor %}


    <button type="submit">Регистрация</button>
</form>
 
{% endblock %}

warehouseDRF/ACCOUNTING/regusers/templates/regusers/restore_password.html
<h1>Здравствуйте</h1>
<h5>Перейдите по ссылке чтобы задать новый пароль</h5>

<h1>{{ protocol }}://{{ domain }}{% url 'regusers:restore_password_url' uidb64=uid token=token %}</h1>

warehouseDRF/ACCOUNTING/regusers/templates/regusers/test.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

</body>
</html>

warehouseDRF/ACCOUNTING/regusers/templates/regusers/user_active.html
<h1>Здравствуйте</h1>
<h5>Перейдите по ссылке чтобы закончить регистрацию</h5>

<a href="{{ protocol }}://{{ domain }}{% url 'regusers:activate_user' uidb64=uid token=token %}"><h1>ССЫЛКА</h1></a>